### ISSUE TITLE
PipelineOptions() error

### ISSUE THREAD

**Issue by yl3394** [GoogleCloudPlatform/DataflowPythonSDK#37]
When I tried to create a pipeline, I kept receiving this type of errors. Does any one know how to solve this? Thanks! 
`import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions

p = beam.Pipeline(options=PipelineOptions())`

`ValueError: ('Parameter options, if specified, must be of type PipelineOptions. Received : %r', <apache_beam.options.pipeline_options.PipelineOptions object at 0x10cb3dd90>)`

**Comment by aaltay** [comment]
Hey @yl3394, what SDK you are using? Can you also share the rest of your code, nothing seems wrong from those 3 lines.

**Comment by b01902041** [comment]
@yl3394 I have the same problem. Did you solve it? If you have solved it, can you please tell me how to?
Thanks!!

**Comment by aaltay** [comment]
@b01902041 what is the version of the SDK you are using? Are you using a new virtualenv? Is it possible that you are mixing two SDK versions somehow?

**Comment by b01902041** [comment]
Hi @aaltay, Thanks for your reply.
I use google-cloud-dataflow 2.0.0
and the virtualenv version is 15.1.0

I think I don't use mixed sdk, since that below:
> pip show google-cloud-dataflow
---
Name: google-cloud-dataflow
Version: 2.0.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: avro, crcmod, dill, grpcio, httplib2, mock, oauth2client, protobuf, pyyaml, google-apitools, proto-google-cloud-datastore-v1, googledatastore, google-cloud-bigquery


When I run this tutorial I have error the same as @yl3394:
https://cloud.google.com/blog/big-data/2016/12/how-to-classify-images-with-tensorflow-using-google-cloud-machine-learning-and-cloud-dataflow

And when I run the tutorial of google cloud dataflow:
https://cloud.google.com/dataflow/docs/quickstarts/quickstart-python
I have another error:

INFO:root:1501042166981: 2017-07-26T04:09:26.981Z: JOB_MESSAGE_ERROR: (dbd152676b686ed1): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 705, in run
    self._load_main_session(self.local_staging_directory)
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 445, in _load_main_session
    pickler.load_session(session_file)
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 247, in load_session
    return dill.load_session(file_path)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 363, in load_session
    module = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python2.7/dist-packages/dill/dill.py", line 423, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named pipeline_options

Do you know how to fix it? Thanks again!

**Comment by b01902041** [comment]
I fixed it by removing apache_beam 0.6.0.
Thank you!!

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
