### ISSUE TITLE
Unable to process anything in beam 2.0.0

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/DataflowPythonSDK#40]
Code that previously worked, does not work anymore in beam 2.0.0.

I have a bigquery input and a simple FlatMap processor.

I keep on getting 

`  (dc39efa8f477bff): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 581, in do_work
    work_executor.execute()
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/executor.py", line 166, in execute
    op.start()
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/native_operations.py", line 48, in start
    for value in reader:
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/nativefileio.py", line 186, in __iter__
    for eof, record, delta_offset in self.read_records():
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/nativeavroio.py", line 102, in read_records
    assert block.num_records() > 0
AssertionError`

**Comment by aaltay** [comment]
@gpopovic - Were you running with 0.6.0 before?

cc: @chamikaramj

**Comment by chamikaramj** [comment]
This is a known issue. See the link below.
https://stackoverflow.com/questions/44791065/asserterror-while-reading-rows-via-bigquery-reader-in-python-google-cloud-datafl

Next version of Beam/Dataflow will include the fix. Beam Head should not run into this after https://github.com/apache/beam/pull/3701 is in.

**Comment by meredithslota** [comment]
## We moved to Apache Beam!
Google Cloud Dataflow for Python is now Apache Beam Python SDK and the code development moved to the [Apache Beam repo](https://github.com/apache/beam/tree/master/sdks/python).

If you want to contribute to the project (please do!) use this [Apache Beam contributor's guide](http://beam.incubator.apache.org/contribution-guide/). Closing out this issue accordingly.
