### ISSUE TITLE
Can't import apache_beam

### ISSUE THREAD

**Issue by thelonelyvulpes** [GoogleCloudPlatform/DataflowPythonSDK#46]
used 'pip install google-cloud-dataflow' from inside virtualenv, any time I try to access apache_beam I get a spew of errors

(dataflow_lab) C:\Users\grant.lodge\dataflow_lab>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import apache_beam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\__init__.py", line 78, in <module>
    from apache_beam import io
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\__init__.py", line 21, in <module>
    from apache_beam.io.avroio import *
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\avroio.py", line 29, in <module>
    from apache_beam.io import filebasedsource
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\filebasedsource.py", line 33, in <module>
    from apache_beam.io.filesystems import FileSystems
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\filesystems.py", line 31, in <module>
    from apache_beam.io.gcp.gcsfilesystem import GCSFileSystem
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\gcp\gcsfilesystem.py", line 27, in <module>
    from apache_beam.io.gcp import gcsio
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\io\gcp\gcsio.py", line 36, in <module>
    from apache_beam.utils import retry
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apache_beam\utils\retry.py", line 38, in <module>
    from apitools.base.py.exceptions import HttpError
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apitools\base\py\__init__.py", line 21, in <module>
    from apitools.base.py.base_api import *
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apitools\base\py\base_api.py", line 31, in <module>
    from apitools.base.protorpclite import message_types
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apitools\base\protorpclite\message_types.py", line 25, in <module>
    from apitools.base.protorpclite import messages
  File "C:\Users\grant.lodge\dataflow_lab\lib\site-packages\apitools\base\protorpclite\messages.py", line 1165, in <module>
    class Field(six.with_metaclass(_FieldMeta, object)):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Python 2.7.14
virtualenv 15.1.0
pip 9.0.1
dataflow 2.1.0
Windows 10 using cmd

**Comment by charlesccychen** [comment]
Hi there, please run `pip install six==1.10`. This is a known issue in Beam (https://issues.apache.org/jira/browse/BEAM-2964) which we are trying to get fixed upstream.

**Comment by thelonelyvulpes** [comment]
this does work. Should I leave the issue open until it is fixed upstream?
