### ISSUE TITLE
Conflict with gcloud pip import

### ISSUE THREAD

**Issue by sthomp** [GoogleCloudPlatform/DataflowPythonSDK#8]
I have a requirements.txt file that looks like this:

```
https://github.com/GoogleCloudPlatform/DataflowPythonSDK/archive/v0.2.2.tar.gz
gcloud==0.11.0
```

There seems to be a conflict with these two imports as I am getting this error:

```
Traceback (most recent call last):
  File "/ingestion_flow/env/bin/../lib/python2.7/site.py", line 703, in <module>
    main()
  File "/ingestion_flow/env/bin/../lib/python2.7/site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "/ingestion_flow/env/bin/../lib/python2.7/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/ingestion_flow/env/bin/../lib/python2.7/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/ingestion_flow/env/bin/../lib/python2.7/site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyError: 'google'
```

I get this error error both when I try to run my application locally using `python main.py`  and also the error persists if I remove gcloud from my requirements.txt and re-run `pip install -r requirements.txt`. The only way to get things working again is to delete my virtualenv and create a new one without the gcloud dependency. 

I spoke to @silviulica who suggested there could be a conflict with the protobuf library.

**Comment by silviulica** [comment]
This should be fixed in v0.2.3 just released.
